### ISSUE TITLE
Invalid key_name provided.

### ISSUE THREAD

**Issue by gimballock** [mohitsethi/vagrant-hp#2]
I'm not sure if this this the best place for my issue but i'm using vagrant 1.4.3 (i was unable to install this plugin on v1.3.5 so i upgraded to latest yesterday).  Now reading all info on this project i can find I still get 400 response every time with message "Invalid key_name provided."

Using the following provider block
config.vm.provider :hp do |rs|
      rs.access_key  = -omitted-
      rs.secret_key = -omitted-
      rs.flavor   = "standard.small"
      rs.tenant_id = -omitted-
      rs.server_name = "vagrant_test"
      rs.image    = "Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)"
      rs.keypair_name = "PlatformD"
      rs.key_name = "PlatformD" #test - no change if included or not
      rs.ssh_private_key_path = "~/.ssh/"
      rs.ssh_username = "ubuntu"
      rs.availability_zone = "az1"
      # Security Groups defaults to ["default"]
      # rs.security_groups = ["group1", "group2"]
end

on the dummy vagrant box

$ vagrant up --provider=hp
Bringing machine 'default' up with 'hp' provider...
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
[default] Warning! The HP provider doesn't support any of the Vagrant
high-level network configurations (`config.vm.network`). They
will be silently ignored.
[default] Finding flavor for server...
[default] Finding image for server...
[default] Launching a server with the following settings...
[default]  -- Flavor: standard.small
[default]  -- Image: Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)
[default]  -- Name: vagrant_test
/home/gimballock/.vagrant.d/gems/gems/excon-0.25.3/lib/excon/middlewares/expects.rb:6:in `response_call': Expected(202) <=> Actual(400 Bad Request) (Excon::Errors::BadRequest)
  response => #<Excon::Response:0x000000042d9840 @data={:body=>"{\"badRequest\": {\"message\": \"Invalid key_name provided.\", \"code\": 400}}", :headers=>{"nnCoection"=>"close", "Content-Length"=>"70", "Content-Type"=>"application/json; charset=UTF-8", "Date"=>"Thu, 16 Jan 2014 20:48:33 GMT"}, :status=>400, :remote_ip=>"168.87.243.141"}, @body="{\"badRequest\": {\"message\": \"Invalid key_name provided.\", \"code\": 400}}", @headers={"nnCoection"=>"close", "Content-Length"=>"70", "Content-Type"=>"application/json; charset=UTF-8", "Date"=>"Thu, 16 Jan 2014 20:48:33 GMT"}, @status=400, @remote_ip="168.87.243.141">
    from /home/gimballock/.vagrant.d/gems/gems/excon-0.25.3/lib/excon/middlewares/response_parser.rb:8:in`response_call'
    from /home/gimballock/.vagrant.d/gems/gems/excon-0.25.3/lib/excon/connection.rb:349:in `response'
    from /home/gimballock/.vagrant.d/gems/gems/excon-0.25.3/lib/excon/connection.rb:247:in`request'
    from /home/gimballock/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/core/connection.rb:57:in `request'
    from /home/gimballock/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/core/deprecated/connection.rb:20:in`request'
    from /home/gimballock/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/hp/compute.rb:227:in `request'
    from /home/gimballock/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/hp/requests/compute/create_server.rb:94:in`create_server'
    from /home/gimballock/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/hp/models/compute/server.rb:239:in `save'
    from /home/gimballock/.vagrant.d/gems/gems/fog-1.15.0/lib/fog/core/collection.rb:52:in`create'
    from /home/gimballock/.vagrant.d/gems/gems/vagrant-hp-0.1.2/lib/vagrant-hp/action/create_server.rb:58:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in`call'
    from /home/gimballock/.vagrant.d/gems/gems/vagrant-hp-0.1.2/lib/vagrant-hp/action/warn_networks.rb:19:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in`call'
    from /home/gimballock/.vagrant.d/gems/gems/vagrant-hp-0.1.2/lib/vagrant-hp/action/sync_folders.rb:22:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in`call'
    from /home/gimballock/.vagrant.d/gems/gems/vagrant-omnibus-1.2.1/lib/vagrant-omnibus/action/install_chef.rb:42:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/provision.rb:52:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in`call'
    from /home/gimballock/.vagrant.d/gems/gems/vagrant-hp-0.1.2/lib/vagrant-hp/action/connect_hp.rb:38:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in`busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/call.rb:51:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/builder.rb:116:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/util/busy.rb:19:in`busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/runner.rb:69:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/machine.rb:147:in`action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'

**Comment by mohitsethi** [comment]
Already fixed in v0.1.3
