### ISSUE TITLE
Permissions on ssh_private_key_path are set to 600

### ISSUE THREAD

**Issue by gimballock** [mohitsethi/vagrant-hp#3]
vagrant up modifies permissions on entire directory to 600.  When this is your ~/.ssh dir it prevents the usage of those keys until you set it back.

before: drwxrwxr-x
after: drw-------

**Comment by gimballock** [comment]
It appears that this is a usage error.

I assume this behavior is coming from net-ssh gem.  When the value of ssh_private_key_path is the entire path _including_ the key name everything works fine. The key's permissions are set to 600 if needed as required by ssh.

If on the other hand this value is a directory (key name not included) the entire directory is set to 600 if not already 600. This is incorrect behavior and things get weird if this happens.

Would be nice if read me or example text show that the expected value was a file path not just a directory path.

**Comment by mohitsethi** [comment]
@gimballock vagrant is actually changing these permissions https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/ssh.rb#L42

**Comment by mohitsethi** [comment]
Not really a issue. Closing it.
