### ISSUE TITLE
Floating Ip issue

### ISSUE THREAD

**Issue by rk3** [mohitsethi/vagrant-hp#8]
Hi,

For me it looks like that the option rs.floating_ip is not used. My boxes always get a new IP Address and never use the ip I provided in this option. 
I deploy to a HP Cloud V13.5 Compute instance. 
I know HP changed the behavior for fixed/floting IP addresses. Maybe this is related to this change but how I can define an IP Address.

Thanks
    Ralf

**Comment by mohitsethi** [comment]
Changes for using existing floating_ip are available in repo, just not yet published to rubygems.org. You can checkout source code, build& install gem.

**Comment by mohitsethi** [comment]
@rk3 v0.1.4 has been released. Feel free to reopen if issue persists with v0.1.4.
