### ISSUE TITLE
keep getting "tenant not found" but I am sure my info is correct

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [mohitsethi/vagrant-hp#9]
What should I do to debug the issue?

**Comment by mohitsethi** [comment]
@guy-mograbi-at-gigaspaces not sure if this is really an issue, but you can enable debug (export EXCON_DEBUG=true, export DEBUG=true, export VAGRANT_LOG=debug) and verify what tenant is being sent to HPCloud API.
